### ISSUE TITLE
non-deterministic machine state

### ISSUE THREAD

**Issue by samueltc** [irobayna/stupidedi#133] opened 2018-09-07 19:03 UTC
Hi @irobayna,

I tried to expand v4010/SH856 to support more segments but I end up with that error:

```
$ ruby write856.rb 
/Users/samueltc/corbeille/ppp/stupidedi/lib/stupidedi/builder/builder_dsl.rb:50:in `segment!': non-deterministic machine state: N1 Name, N1 Name (Stupidedi::Exceptions::ParseError)
	from /Users/samueltc/corbeille/ppp/stupidedi/lib/stupidedi/builder/builder_dsl.rb:100:in `method_missing'
	from write856.rb:39:in `<main>'
```

I created a branch if you want to reproduce:

https://github.com/samueltc/stupidedi/tree/SH856-dont-merge

Here is the spec I got from the vendor: [856 ASN version 4010_edited.pdf](https://github.com/irobayna/stupidedi/files/2362184/856.ASN.version.4010_edited.pdf)

All the best,

Sam

**Comment by irobayna** [comment] 2018-09-13 13:08
@samueltc The non-deterministic error is to be expected if the library cannot uniquely identify a particular segment.  I have not been able to look at your branch but in the meantime, is there a way to add more info to the particular segment (add more data).  More than likely the issue will go away.

**Comment by phildionne** [comment] 2018-09-18 19:48
I have the same issue with SH856. I think it's not the first time someone has an issue with this, see this issue https://github.com/irobayna/stupidedi/issues/55 for SH856 as well.

I'm getting error: 

```
stupidedi/lib/stupidedi/builder/builder_dsl.rb:50:in `segment!': non-deterministic machine state: N1 Name, N1 Name (Stupidedi::Exceptions::ParseError)
	from /Users/pdionne/Dev/samueltc/stupidedi/lib/stupidedi/builder/builder_dsl.rb:100:in `method_missing'
```

Here's the relevant code:

```ruby
require "./lib/stupidedi"

config = Stupidedi::Config.contrib(Stupidedi::Config.default)

b = Stupidedi::Builder::BuilderDsl.build(config)

po_number = "1D111888"
receiver_code = "10401111T"
sender_code = "010020001"
vendor_code = "AA"
interchange_sender_id = "#{sender_code}-#{vendor_code}"
isa_control_number = "000001"
gs_control_number = "000002"
st_control_number = "000003"

shipment_identification = "ID1234567"

b.ISA "00", nil, "00", nil,
      "ZZ", interchange_sender_id,
      "01", receiver_code,
      Time.now.utc, Time.now.utc, "U", "00400", isa_control_number, "0", "T", "#"

b.GS "SH", sender_code, receiver_code, Time.now.utc, Time.now.utc, gs_control_number, "X", "004010"

# Header
b.ST "856", st_control_number
b.BSN "00", shipment_identification, Time.now.utc, Time.now.utc
b.DTM "011", Time.now.utc, Time.now.utc

# Detail
b.HL "1", nil, "S", "1"
  b.MEA "PD", "G", "3401", "LB"
  b.MEA "PD", "N", "3400", "LB"
  b.TD1 "PLT", "3"
  b.TD5 "B", "25", "SAMEDAYRIGHT-O-WAY", "L", nil
  b.TD3 "TL", shipment_identification
  b.REF "BM", shipment_identification

b.N1 "SU", "PARTS CANADA", "92", interchange_sender_id
  b.N3 "65 MAIN ST."
  b.N4 "LAVAL", "QC", "H0H 0H0", "CAN"

b.HL "2", "1", "O", "1"
  b.PRF po_number
  b.REF "MH", po_number

b.N1 "ST", "RICHMOND PDC PARTS DIST CENTRE", "92", receiver_code
  b.N3 "30 PROGRESS AVE"
  b.N4 "SCARBOROUGH", "ON", "M1H2X5", "CAN"

b.HL "3", "2", "I", "0"
  b.LIN "1", "BP", "C000202"
  b.SN1 nil, "40", "PC"

b.machine.zipper.tap do |z|
  separators =
    Stupidedi::Reader::Separators.build segment: "~\n",
                                        element: "*",
                                        component: ":",
                                        repetition: "^"

  w = Stupidedi::Writer::Default.new(z.root, separators)
  print w.write()
end
```

```ruby
module Stupidedi
  module Contrib
    module FortyTen
      module TransactionSetDefs

        d = Schema
        r = SegmentReqs
        s = SegmentDefs

        SH856 = d::TransactionSetDef.build("SH", "856", "Ship Notice/Manifest",

          d::TableDef.header("Table 1 - Header",
            s:: ST.use(10, r::Mandatory, d::RepeatCount.bounded(1)),
            s::BSN.use(20, r::Mandatory, d::RepeatCount.bounded(1)),
            s::DTM.use(40, r::Optional,  d::RepeatCount.bounded(10))
          ),

          d::TableDef.detail("Table 2 - Detail",
            d::LoopDef.build("HL", d::RepeatCount.bounded(200000),
              s:: HL.use( 10, r::Mandatory, d::RepeatCount.bounded(1)),
              s::MEA.use( 80, r::Optional,  d::RepeatCount.bounded(40)),
              s::TD1.use(110, r::Optional,  d::RepeatCount.bounded(20)),
              s::TD5.use(120, r::Optional,  d::RepeatCount.bounded(12)),
              s::TD3.use(130, r::Optional,  d::RepeatCount.bounded(12)),
              s::TD4.use(140, r::Optional,  d::RepeatCount.bounded(5)),
              s::REF.use(150, r::Optional,  d::RepeatCount.unbounded)
            ),

            d::LoopDef.build("N1", d::RepeatCount.bounded(200),
              s::N1.use(220, r::Optional,  d::RepeatCount.bounded(1)),
              s::N3.use(240, r::Optional,  d::RepeatCount.bounded(2)),
              s::N4.use(250, r::Optional,  d::RepeatCount.bounded(1))
            ),

            d::LoopDef.build("HL", d::RepeatCount.bounded(200000),
              s:: HL.use( 10, r::Mandatory, d::RepeatCount.bounded(1)),
              s::PRF.use( 50, r::Optional,  d::RepeatCount.bounded(1)),
              s::REF.use(150, r::Optional,  d::RepeatCount.unbounded)
            ),

            d::LoopDef.build("N1", d::RepeatCount.bounded(200),
              s::N1.use(220, r::Optional,  d::RepeatCount.bounded(1)),
              s::N3.use(240, r::Optional,  d::RepeatCount.bounded(2)),
              s::N4.use(250, r::Optional,  d::RepeatCount.bounded(1))
            ),

            d::LoopDef.build("HL", d::RepeatCount.bounded(200000),
              s:: HL.use(10, r::Mandatory, d::RepeatCount.bounded(1)),
              s::LIN.use(20, r::Optional,  d::RepeatCount.bounded(1)),
              s::SN1.use(30, r::Optional,  d::RepeatCount.bounded(1))
            ),
          ),

          d::TableDef.summary("Table 4 - Summary",
            s::CTT.use(10, r::Optional,  d::RepeatCount.bounded(1)),
            s:: SE.use(20, r::Mandatory, d::RepeatCount.bounded(1))
          )
        )
      end
    end
  end
end
```

@irobayna any insights into wether that's to be expected or it's a bug/limitation in the parsing logic?

Thanks

**Comment by irobayna** [comment] 2018-09-19 01:41
@phildionne The issue you point out is not for generating a transaction bur for parsing one.  The logic is quite different.  If you read Kyles response the problem is not a limitation or a bug of the library but rather being able to uniquely identify the segments.  I have struggled with this issue as well at times.

I have used this message  v2001 which I know works.

**Comment by kputnam** [comment] 2018-12-03 22:36
Hi @phildionne, the issue is that when the parser reads the N1 segment, it doesn't know where in the document it's supposed to go. This isn't a problem in general, but with certain schemas. Notice there are two loops starting with an N1 segment in your transaction set definition.

Sometimes the next segment will constrain the set of choices (eg, maybe one loop has an XYZ segment and the other does not), but in your case the loops look identical in terms of which segments go in them.

My advice is to avoid ambiguity all together, even if it could theoretically be resolved by reading another segment or two -- because until it's resolved, the parser keeps multiple parse trees and updates each one, which is slower and takes more memory than updating one parse tree.

To avoid ambiguities, you can add some restrictions on the elements in your N1 segments. For instance, maybe the first N1 loop can only have N1*88, N1*89, N1*90 or some other subset of codes in one of the N1 elements. Next you need to put constraints on the other N1 segment. These will let the parser rule out one or the other segment when it reads an N1, and you won't have this problem.

This requires that you build a Guide on top of your TransactionSetDef, and use that as the schema rather than using only the TransactionSetDef. For examples of how this is done, look at the other guides -- particularly ones with N1 segments. You'll also probably need some documentation from your trading partner or elsewhere, to know which values are allowed in each segment.

**Comment by kputnam** [comment] 2018-12-16 07:42
The schema you pasted didn't look right, so I took another look at this. I think what happened was in 048e54cb316974a3c50808fc68f06f8dc64c9c40, this transaction set definition was created from an implementation guide instead of a transaction set definition document.

**Problem:**

Skimming Google for "4010 SH 856" shows many implementation guides that more or less look like the one you pasted. In these, there are multiple `HL` and `N1` loops that are variations of one another, but the attributes that distinguish one from another are *missing* in this `TransactionSetDef`. Those kinds of details would go in a `Guide`. 

The `TransactionSetDef` should instead have a "most general `HL` loop" and a "most general `N1` loop" that contains all the possible segments that could *ever* occur in that `HL` or `N1`  loop.

**Solution:**

Ideally you would have the definitive X12 transaction set documentation, but without that, you can guess what some of the real `TransactionSetDef` looks like like by combining all the related `HL` loops from the implementation guide into one big general `HL` loop  (of which all other examples of an `HL` loop are compatible). Because each implementation guide only has some subset of the actual transaction set definition, your guess will be incomplete, but the next person can add more segments or loops onto it.

That's all fine, but what you ultimately will want is your own `Guide` that's made from the documentation given by your trading partner. So take a look at the other `Guide`s in this repository and see how they correspond to documents like [this one](https://www.hfi-inc.com/wp-content/uploads/2015/10/X124010856Specifications.pdf) or [this one](https://www.generalmills.com/~/media/Images/GMI/TradingPartners/NorthAmerica/SO_856_X12_4010_I59.pdf?la=en) or [this one](https://www.biglots.com/images/marketing/corporate/vendors/edi/X12_856_SH_5010_Domestic_Vendor_Compliance_R73_20130708.pdf).

The important parts are the allowed value constraints in the elements of each segment. For instance, the page about first `HL` loop might say `HL-03` must have an `O` in it, while the page about the second `HL` loop says `HL-03` must have an `I`. That's how the parser will tell them apart: if it reads a `HL` segment, it knows which loop to choose based on the value in `HL-03`.

So I would recommend starting with creating the `Guide` and then work backward to make your own `TransactionSetDef` that generalizes it. The 4010 `SH856` transaction set definition we have in the repo currently is not usable, probably for anyone, so if you do create your own, please consider submitting it as a pull request!

**Closed by kputnam** 2018-12-16 07:42 UTC

**Comment by kputnam** [comment] 2018-12-23 05:31
My mistake, I didn't realize the definition you pasted was different from what's in the repo to start with. I've been working on a way to catch these errors in the specs, before they get committed to the repository. But the definition for `SH856` in the repository is actually okay.

What I said earlier is still true. But it looks like you added more `N1` and `HL` loops? Take a look at the corresponding [`Guide` for `SH856`](https://github.com/irobayna/stupidedi/blob/master/lib/stupidedi/contrib/004010/guides/SH856.rb). It has two `HL` loops, but the first declares `HL-03` must have the value `S`; the second `HL-03` must have the value `T`. That way the parser can tell which one to instantiate when it reads an `HL` segment in the input.

I'm guessing you didn't realize this guide existed, so you were adding stuff to the wrong place. Try using `Stupidedi::Contrib::FortyTen::Guides::SH856` instead and see if that works without needing to change the definition. You might need to either extend that definition, or create a separate one.

Hope that helps!

**Comment by MattJordan** [comment] 2020-10-07 20:22
Hi.folks. I have this same issue, also with a customized/expanded SH856, specifically with HLs. It looks like guides are deprecated in favor of implementations as of 1.4, so how would I solve this problem in 1.4? Thanks for any help.
