### ISSUE TITLE
problems customizing a transaction set

### ISSUE THREAD

**Issue by alexdean** [irobayna/stupidedi#231] opened 2020-12-30 22:04 UTC
I've run into a case where a trading partner requires an additional element which is not part of a segment's standard definition. I'm trying to follow @kputnam's advice in [this comment](https://github.com/irobayna/stupidedi/issues/222#issuecomment-639910514) and define a custom implementation/guide for this partner.

The trouble I'm having is that even when I've defined a new set of elements for a segment, stupidedi reports an error "N1 segment has only 6 elements". (Where 6 is the [original number of elements in the N1 segment](https://github.com/irobayna/stupidedi/blob/dc9b8b5a25b2d62f1ae74bcf731e332bd70b9ebf/lib/stupidedi/versions/004010/segment_defs/N1.rb#L12-L17).)

I've created [a gist](https://gist.github.com/alexdean/1869b6e5584179f295008612689abcfb) which can be used to reproduce the error I'm seeing. Gist also includes a stack trace for the error.

Could someone help me understand if I'm doing something wrong here, or if this is a stupidedi bug of some kind? (If so, I am happy to try a fix if I can get some guidance on what needs to change...)

**Comment by kputnam** [comment] 2020-12-31 01:39
Hey Alex,

Thanks for the detailed report, especially the code. Now that I've actually read the full example, I can delete my very long response, and the issue is trickier than I anticipated! :-)

There's nothing wrong with your definition. I think the problem is how Stupidedi looks up the segment definitions when reading a file or building one with `BuilderDsl`. My recollection is that it goes like this: you call `b.N1` and `BuilderDsl` looks up the definition for `N1` in the `SegmentDefs` module for the version you're using (`FortyTen`). That association is made when you register the 4010 functional group in the `Config`.

I need to do some thinking about how/if this could be improved to address your issue, since the underlying assumption is that there's a single definition of a segment for each X12 version. If that assumption is removed, that might allow for different versions of a segment to exist within the same document, and knowing which one to use could be a challenge.

Ideally you wouldn't need to do anything beyond what you've already written, and it would be handled behind the scenes. But in the mean time, I think you can define your own `FunctionalGroupDef` with something like this:

```ruby
module MySegmentDefs
  include Stupidedi::Versions::FortyTen::SegmentDefs
  N1 = ...
  N2 = ...
end

# Despite the capitalization, this is actually a singleton instance of an anonymous class
# that inherits from Values::FunctionalGroupDef. We need to override one method.
MyFunctionalGroupDef = Stupidedi::Versions::FortyTen::FunctionalGroupDef.clone

class << MyFunctionalGroupDef
  def segment_dict
    MySegmentDefs

    # You can also not use `include` in the module above and do this instead
    # Stupidedi::Reader::SegmentDict.build(super).push(MySegmentDefs)
  end
end

config.functional_group.register("004010") { MyFunctionalGroupDef }
```

There are a few different ways to write that, but I think that's clearest.

**Comment by alexdean** [comment] 2021-01-04 16:06
@kputnam thanks a million for this input. i've tried out your suggestions and it seems to behave just as i'd expect. i can add/remove elements from segments with a minimum of fuss. this is excellent. (Much better than the dirty hacks we've been doing (like modifying `Stupidedi::TransactionSets::FortyTen::Implementations::IM210.table_defs` at runtime to patch in our modified segment definition...)

>  I think the problem is how Stupidedi looks up the segment definitions when reading a file or building one with BuilderDsl. 

yes, and this was part of the stupidedi code i was never able to piece together on my own. your explanation clears it up nicely.

> Ideally you wouldn't need to do anything beyond what you've already written, and it would be handled behind the scenes.

Perhaps, but so far it seems like the alternative you've offered here will serve nicely. I'll try unwinding some of our current hacks and see if I can straighten things out using the approach you describe here. Assuming that goes OK I don't see any need for further action - though a "how to customize segment definitions" guide might be a useful addition.

**Comment by kputnam** [comment] 2022-03-04 23:41
Hey Alex, I'm going to close this issue. It sounds like you're okay with the proposed solution and I think a better looking solution will take more time than it's worth. I agree on having a guide that walks through various configuration scenarios, but I don't know that I'll be able to set aside time for that in the near future.

**Closed by kputnam** 2022-03-04 23:41 UTC
Labels: defect, limitation
