### ISSUE TITLE
Incompatibility with factory_bot gem

### ISSUE THREAD

**Issue by coenwulf** [irobayna/stupidedi#182] opened 2019-03-09 00:24 UTC
If my rails project includes both `stupidedi` and `factory_bot` then rails console and rspec don't work correctly.
Trying to run a rails console leads to:
```
/Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/factory_bot-4.8.2/lib/factory_bot/definition_proxy.rb:6:in `undef_method': undefined method `blank?' for class `FactoryBot::DefinitionProxy' (NameError)
Did you mean?  blank?
        from /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/factory_bot-4.8.2/lib/factory_bot/definition_proxy.rb:6:in `block in <class:DefinitionProxy>'
        from /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/factory_bot-4.8.2/lib/factory_bot/definition_proxy.rb:5:in `each'
        from /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/factory_bot-4.8.2/lib/factory_bot/definition_proxy.rb:5:in `<class:DefinitionProxy>'
        from /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/factory_bot-4.8.2/lib/factory_bot/definition_proxy.rb:2:in `<module:FactoryBot>'
        from /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/factory_bot-4.8.2/lib/factory_bot/definition_proxy.rb:1:in `<top (required)>'
        from /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
        from /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `block in require'
        from /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
        from /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/factory_bot-4.8.2/lib/factory_bot.rb:35:in `<top (required)>'
        from /Users/jeremy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:81:in `require'
        from /Users/jeremy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:81:in `block (2 levels) in require'
        from /Users/jeremy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:76:in `each'
        from /Users/jeremy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:76:in `block in require'
        from /Users/jeremy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:65:in `each'
        from /Users/jeremy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:65:in `require'
        from /Users/jeremy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/bundler.rb:114:in `require'
        from /Users/jeremy/projects/tip_portal/config/application.rb:7:in `<top (required)>'
        from /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:156:in `require'
        from /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:156:in `require_application_and_environment!'
        from /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:77:in `console'
        from /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/railties-5.0.6/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:9:in `require'
        from bin/rails:9:in `<main>'
```

Trying to run rspec leads to:
```
NameError:
  undefined method `present?' for class `FactoryBot::DefinitionProxy'
  Did you mean?  present?
                 presence
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/factory_bot-4.8.2/lib/factory_bot/definition_proxy.rb:6:in `undef_method'
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/factory_bot-4.8.2/lib/factory_bot/definition_proxy.rb:6:in `block in <class:DefinitionProxy>'
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/factory_bot-4.8.2/lib/factory_bot/definition_proxy.rb:5:in `each'
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/factory_bot-4.8.2/lib/factory_bot/definition_proxy.rb:5:in `<class:DefinitionProxy>'
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/factory_bot-4.8.2/lib/factory_bot/definition_proxy.rb:2:in `<module:FactoryBot>'
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/factory_bot-4.8.2/lib/factory_bot/definition_proxy.rb:1:in `<top (required)>'
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `block in require'
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/factory_bot-4.8.2/lib/factory_bot.rb:35:in `<top (required)>'
# ./config/application.rb:7:in `<top (required)>'
# ./config/environment.rb:2:in `require_relative'
# ./config/environment.rb:2:in `<top (required)>'
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `block in require'
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
# ./spec/rails_helper.rb:3:in `<top (required)>'
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `block in require'
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
# ./spec/whenever/get_orders_on_day_spec.rb:1:in `<top (required)>'
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `block in load'
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
# /Users/jeremy/.rvm/gems/ruby-2.3.1@tip_portal/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
```
Removing either gem stops the error. Any idea why these two gems are incompatible?

**Comment by kputnam** [comment] 2019-03-09 00:46
Hmm, which version of stupidedi are you using? Long ago, stupidedi used monkey-patching to implement `#blank?` and that caused lots of havoc.

**Comment by kputnam** [comment] 2019-03-09 00:46
Also, to be clear, you only have a problem when including all **three** gems?

**Comment by kputnam** [comment] 2019-03-09 00:54
Sorry for the rapid-fire messages, but I wonder if whatever object you're proxying `#respond_to?(:blank)` or `#respond_to?(:present?)` but they can't be called/removed by factory bot because they aren't in scope somehow.

I don't think we override `#respond_to?`, `Class#methods` or `#instance_methods` anywhere. Can you tell me what object is being passed to factory bot's definition proxy, and have you written `using Stupidedi::Refinements` anywhere?

**Comment by coenwulf** [comment] 2019-03-11 17:15
Thanks for the responses:
It looks like the version of stupidedi that's getting installed is 1.3.23.
I hadn't tried without rspec before, but removing rspec, when I have both stupidedi and factory_bot doesn't seem to help. It still fails to start a console.
Since this is a rails project I haven't tried removing all of the rails related gems.
I haven't written any stupidedi related code yet. I encountered this just by adding stupidedi to my Gemfile, bundling, and starting a console. I was hoping to try out stupidedi to see if I could use it to parse 214 messages. 
To try to narrow down the potential causes as much as possible I created a new blank rails project, with pretty basic settings (using postgresql, but otherwise pretty much stock). I added the relevant gems (stupidedi and factory_bot) to the Gemfile and tried to start a console. I get the same behavior there, so I'm pretty certain it's not a result of any modifications in my code. Just to be certain, I've done a project wide search for stupidedi in my sample project and it is only referenced in Gemfile and Gemfile.lock.
I'll be happy to try things to attempt to narrow down the cause.

**Comment by coenwulf** [comment] 2019-03-11 17:24
Hmm, this is interesting. In the stupidedi code that's installed I found code defining `blank?` and `present?` in `lib/ruby/array.rb`, `lib/ruby/blank.rb`, `lib/ruby/jruby_hack.rb`, and just `blank?` in several more.
Is 1.3.23 an old version that I shouldn't be using?

**Comment by kputnam** [comment] 2019-03-11 18:32
Those definitions for `#blank?` are inside a `refine <class> ... end` block, so they're only brought into scope when you write `using Stupidedi::Refinements`. But there could still be something strange going on there... I would look at the factory-bot files from the stack trace to see why it's trying to remove `#blank?` and `#present?`. Stupidedi's definitions for those methods shouldn't be visible to factory-bot, but perhaps ActiveSupport monkey-patched them in. Even so, I don't know why it would cause that problem you're seeing.

However, if you're using JRuby, refinements were broken for a long time and `jruby_hack.rb` does use monkey patching, so that would be one potential explanation for what you're seeing. You might also double check that if you've installed 1.3.23, that `Stupidedi::VERSION` reports that version number and/or the files in `stupidedi/lib/ruby` match those from [the 1.3.23 tag](https://github.com/irobayna/stupidedi/tree/1.3.23/lib/ruby). I think 1.3.23 is the most recent release, so you aren't out of date.

If you are using JRuby, recently we've removed jruby_hack, but I haven't tested with JRuby and I don't think we are testing builds for JRuby on Travis CI either. I don't think that change is released or even in `master` yet, so if you want to try it you've got two options: (a) install from the `pr-reorganize` branch or (b) edit `lib/stupidedi.rb` and manually remove the line that requires `jruby_hack`. Beware that `pr-reorganize` is still under development and likely has new bugs or regressions that need to be fixed before it's merged and released!

**Comment by coenwulf** [comment] 2019-03-11 19:26
Thank you. No, I'm not using JRuby. It's ruby 2.3.1. (I also accidentally tested it on ruby 2.5.0.)
Yeah, I can confirm that it's definitely version 1.3.23 based on what `lib/stupidedi/version.rb` contains.

Looking in factory_bot, it looks like it's trying to undefine all instance methods and private method except for a short list of white-listed methods. The relevant code is:
```
    UNPROXIED_METHODS = %w(
      __send__
      __id__
      nil?
      send
      object_id
      extend
      instance_eval
      initialize
      block_given?
      raise
      caller
      method
    ).freeze

    (instance_methods + private_instance_methods).each do |method|
      undef_method(method) unless UNPROXIED_METHODS.include?(method.to_s)
    end
```
It's that `undef_method(method)` that is triggering the failure.
Given that it in a class named `DefinitionProxy`, I'm guessing that it's trying to clear potential definitions for things that should be proxied to some other class. 
I don't know why those methods are causing problems though since there's no code for `using Stupidedi::Refinements` I wonder if it's a class loader issue? I know that ActiveSupport does define `#blank?` for multiple classes. The approach they use is slightly different in some cases (e.g., alias_method to empty? rather than calling empty? on Array). But even so, I'm not sure how that is interacting with it.

**Comment by coenwulf** [comment] 2019-03-11 19:31
Interestingly, if I comment out the various definitions for `#blank?`, `#present?`, and `#try` in the refinements classes it at least starts the console.

**Comment by kputnam** [comment] 2019-03-11 19:39
Hmm, to be clear, are you calling factory-bot in your specs or tests to proxy something defined by stupidedi? Or that's just happening in your blank project, without even writing tests?

One thing I noticed is in IRB, not in any particular project, that `"".respond_to?(:blank?)` is false until I `require "stupidedi"`; then it returns true. That's not expected... so I think it could be a bug in stupidedi. I'll take a closer look today.

**Comment by kputnam** [comment] 2019-03-11 19:49
Ok, it seems to be caused by loading `term-ansicolor`. If I uninstall that gem, then `blank?` isn't defined on `String` or `Array`. Do you still get the error with factory-bot if you `gem uninstall term-ansicolor`?

**Comment by coenwulf** [comment] 2019-03-11 20:51
No, I don't have any tests/specs related to or referencing stupidedi yet. The problems happen even in my blank project. Note that I can cause the problem to not happen on console startup if I remove factory_bot from my development environment and just have it in test. However, when I do that I still have the issue I reported related to starting specs (again, despite not having any specs related to stupidedi or even any code in my project using stupidedi). Since that is still a blocker, I have put back the config of using factory_bot in the development environment (since that allows using factory_bot features on my dev platform).
I tried removing term-ansicolor (by commenting out that line in lib/stupidedi.rb and removing the dependency line in Gemfile.lock). I still have the same issues even without term-ansicolor.

**Comment by coenwulf** [comment] 2019-03-27 22:49
I was able to get past this by forking stupidedi and removing `require "ruby/blank"` and `require "ruby/try"` from `lib/stupidedi.rb`. Hopefully that's the only roadblock.

**Comment by kputnam** [comment] 2019-04-04 21:00
I tried to reproduce this by creating a new project (`rails new bug-182`) and running `rails console` using these dependencies:

- factory_bot 5.0.2
- stupideid 1.4.0
- rails 5.2.3
- ruby 2.5.3

I didn't have any problem, but maybe I'm missing something? I also tried using factor_bot 4.8.2 and stupidedi 1.3.23, no issue either. I wasn't able to get ruby 2.3.1 working, because of OpenSSL issues on MacOS. Can you post a short list of steps to reproduce?

Here's mine:

```sh
$ ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]

$ gem install rails --version 5.0.6
$ rails new bug-182
$ cd bug-182
$ echo 'gem "stupidedi"' >> Gemfile
$ echo 'gem "factory_bot"' >> Gemfile
$ bundle install
$ rails console
```

**Comment by coenwulf** [comment] 2019-04-04 23:58
Maybe there's also an issue with ruby 2.3.1. I tried to reproduce it with ruby 2.5.3, and couldn't. However, when I followed the same steps on ruby 2.3.1 it does reproduce the issue.

Here are my steps:
```
rvm use 2.3.1
ruby -v
#ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin18]
rvm 2.3.1@bug-182 --create do gem install rails -v 5.0.6
rvm gemset use bug-182
rails new bug-182 -d postgresql
cd bug-182
echo "gem 'stupidedi'" >> Gemfile
echo "gem 'rspec-rails', '~> 3.0', groups: [:development, :test]" >> Gemfile
echo "gem 'factory_bot', groups: [:development, :test]" >> Gemfile
bundle
rails console
```

**Comment by rndnoise** [comment] 2019-04-17 20:44
Ok, I happened to remember having a Raspberry Pi around and was able to install ruby 2.3 on it via rvm. Everything seemed to work as expected, but I was using ruby 2.3.8; so I'll give it another shot later today with ruby 2.3.1.

**Comment by kputnam** [comment] 2019-04-17 20:45
Ok, I happened to remember having a Raspberry Pi around and was able to install ruby 2.3 on it via rvm. Everything seemed to work as expected, but I was using ruby 2.3.8; so I'll give it another shot later today with ruby 2.3.1.

**Comment by coenwulf** [comment] 2019-04-17 21:03
I think I have a high enough confidence that it's related to the ruby version, since I can't even replicate it on the same laptop when running the newer ruby version. If you want to dig further for your own satisfaction, that's fine. But I will just use a workaround of a fork of the gem without the try and blank refinements. I'm recommending internally that our project upgrades to a newer ruby version and then we'll be able to switch back to the mainline version of stupidedi.

**Comment by kputnam** [comment] 2019-04-17 21:06
OK, I'll leave it alone and close the issue then. Thanks for helping me look into this!

**Closed by kputnam** 2019-04-17 21:06 UTC

**Comment by alex-hedrevich** [comment] 2019-08-23 20:36
I have exactly the same problem. 

After removing from `lib/stupidedi.rb` :

```
require "ruby/array"
require "ruby/blank"
require "ruby/exception"
require "ruby/hash"
require "ruby/module"
require "ruby/object"
require "ruby/string"
require "ruby/to_d"
require "ruby/to_date"
require "ruby/to_time"
require "ruby/try
``` 

Makes the test work. 
Look like `required` loads these into global scope even when `using Refinements` is not used?
